name: Build and Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Instalar Snyk CLI
      - name: Set up Snyk
        uses: snyk/actions/setup@master

      # 2. Ejecutar análisis estático (SAST + SCA)
      - name: Run Snyk test
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium

      # 3. Tag dinámico
      - name: Set dynamic tag
        run: echo "TAG=v$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      # 4. Build de la imagen
      - name: Build Docker image
        run: docker build -t migueldevsec/shield-scan:${{ env.TAG }} .

      # 5. Login a Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      # 6. Push de la imagen
      - name: Push image to Docker Hub
        run: docker push migueldevsec/shield-scan:${{ env.TAG }}